---
route:
  group_by:
    - alertname
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: email-notifications
receivers:
  - name: email-notifications
    email_configs:
      - to: anilpolicepatil18@gmail.com
        from: Monitoring@example.com
        smarthost: smtp.gmail.com:587
        auth_username: anilpolicepatil18@gmail.com
        auth_identity: anilpolicepatil18@gmail.com
        auth_password: qbld albm actw qqkv
        send_resolved: true
inhibit_rules:
  - source_match:
      severity: critical
    target_match:
      severity: warning
    equal:
      - alertname
      - dev
      - instance
